spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8
    username: myhome
    password: myhome

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace